sudo: required

services:
  - docker

env:
  global:
    - USER='jdvelasq'
    - EMAIL='jdvelasq@unal.edu.co'
    - REPO='concept-proof-grade' 
    - GH_REPO='github.com/S{USER}/${REPO}.git' 
    - FILENAME=${PWD##*/}.txt

before_install:
  - docker network create proof-net
  - docker pull mysql:5
  - docker run --rm --name proof-mysql --network=proof-net -e MYSQL_ROOT_PASSWORD=password -d mysql:5
  - docker pull jdvelasq/jupyter-proof
  

script:
  - docker run --rm --network=proof-net --volume="$(pwd)":/home  jdvelasq/jupyter-proof /bin/sh -c "cd home && ./gradetool  sql-grading.ipynb" > grade.txt
  - cat ${FILENAME}
  - mv grade.txt ${PWD##*/}.txt


after_success:
  - git config --global user.email "jdvelasq@unal.edu.co"
  - git config --global user.name "jdvelasq"
  - git clone --quiet https://jdvelasq:${GITHUB_TOKEN}@github.com/jdvelasq/concept-proof-grade.git  ./repo
  - mv ${FILENAME} ./repo/${FILENAME}
  - cd repo
  - echo ${FILENAME}
  - git add ${FILENAME}
  - git commit -m "grading from Travis-CI"
  - git push origin master
  